-- Hyprland configuration
hl.config({ autogenerated = false })

-- ==================
-- STARTUP
-- ==================

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("protonmail-bridge --noninteractive")
end)

-- ==================
-- MAIN CONFIG
-- ==================

hl.config({
	input = {
		kb_layout = "us",
		numlock_by_default = true,
	},

	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},

	decoration = {
		rounding = 12,
		active_opacity = 0.85,
		inactive_opacity = 0.85,

		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = { 0, 5 },
			color = "rgba(00000070)",
		},
	},

	dwindle = {
		preserve_split = true,
	},

	master = {
		mfact = 0.5,
	},

	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		vrr = 1,
	},
})

-- ==================
-- ANIMATIONS
-- ==================

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

-- ==================
-- BASE WINDOW RULES
-- ==================

hl.window_rule({
	match = { class = [[^(org\.wezfurlong\.wezterm)$]] },
	tile = true,
})

hl.window_rule({
	match = { class = [[^(org\.gnome\.)]] },
	rounding = 12,
})

hl.window_rule({
	match = { class = [[^(gnome-control-center)$]] },
	tile = true,
})

hl.window_rule({
	match = { class = [[^(pavucontrol)$]] },
	tile = true,
})

hl.window_rule({
	match = { class = [[^(nm-connection-editor)$]] },
	tile = true,
})

hl.window_rule({
	match = { class = [[^(gnome-calculator)$]] },
	float = true,
})

hl.window_rule({
	match = { class = [[^(galculator)$]] },
	float = true,
})

hl.window_rule({
	match = { class = [[^(blueman-manager)$]] },
	float = true,
})

hl.window_rule({
	match = { class = [[^(org\.gnome\.Nautilus)$]] },
	float = true,
})

hl.window_rule({
	match = { class = [[^(steam)$]] },
	float = true,
})

hl.window_rule({
	match = { class = [[^(xdg-desktop-portal)$]] },
	float = true,
})

hl.window_rule({
	match = {
		class = [[^(firefox)$]],
		title = [[^(Picture-in-Picture)$]],
	},
	float = true,
})

hl.window_rule({
	match = { class = [[^(zoom)$]] },
	float = true,
})

hl.layer_rule({
	match = { namespace = [[^(quickshell)$]] },
	no_anim = true,
})

-- ==================
-- DMS
-- ==================

require("dms.colors")
require("dms.binds")
