-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(8fcdff)",
			inactive_border = "rgb(89929b)",
		},
	},
	group = {
		col = {
			border_active = "rgb(8fcdff)",
			border_inactive = "rgb(89929b)",
			border_locked_active = "rgb(ffb4ab)",
			border_locked_inactive = "rgb(89929b)",
		},
		groupbar = {
			col = {
				active = "rgb(8fcdff)",
				inactive = "rgb(89929b)",
				locked_active = "rgb(ffb4ab)",
				locked_inactive = "rgb(89929b)",
			},
		},
	},
})
